### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by tnjd** [tekknolagi/100prisoners#2]
May I suggest the MPL-2.0?

**Comment by tekknolagi** [comment]
Hi @expectocode ! Sorry for the delayed response. I didn't get a notification for this.

**Comment by tekknolagi** [comment]
I'll consult with the co-authors.

**Comment by tnjd** [comment]
Thanks for your response :)

**Comment by tekknolagi** [comment]
It's looking like MIT is likely. I'll get around to it sometime. If you are feeling particularly helpful you are welcome to submit a license PR :P

**Comment by tnjd** [comment]
I very well may do that - I'm keen to submit some more exciting `r u s t` contributions but would never dream of violating copyright law

**Comment by tekknolagi** [comment]
Oh, sure! It would be fun to have a rust impl alongside Python and C++.

**Comment by tnjd** [comment]
The MIT license requires a name - what do you want there?

**Comment by tekknolagi** [comment]
"Copyright 2019 Maxwell Bernstein, Chris Gregory, Yuki Zaninovich" would be great!

**Comment by tekknolagi** [comment]
I've added MIT.
